export const words = [
  'yo',
  'what\'s good',
  'holla',
  'Detroit',
  'Midwest the best',
  '313',
  'steezy',
  'fo sho',
  'dickies',
  'vans',
  'Dixxon flannels',
  'pizza',
  'rice beer',
  'bud light',
  'gluten free',
  'smoke weed everyday',
  'so fresh so clean',
  'crib',
  'banger',
  'six-four',
  'ridin dirty',
  'hostility',
  'stripper dope'
];